### PR TITLE
Fix arm-none-eabi build (fixes #451)

### LINKED ISSUE #451: Fails to build with arm-none-eabi Newlib toolchain
I am using an arm-none-eabi toolchain (GCC 6.3.0 with Newlib 2.5.0). This is where the build fails:

```
  CXX      libharfbuzz_la-hb-buffer-serialize.lo
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh: In static member function ‘static hb_bool_t hb_unicode_funcs_t::is_variation_selector(hb_codepoint_t)’:
hb-unicode-private.hh:131:26: error: no matching function for call to ‘hb_in_ranges(hb_codepoint_t&, unsigned int, unsigned int, unsigned int, unsigned int)’
        0xE0100u, 0xE01EFu));  /* VARIATION SELECTOR-17..256 */
                          ^
hb-private.hh:78:34: note: in definition of macro ‘_HB_BOOLEAN_EXPR’
 #define _HB_BOOLEAN_EXPR(expr) ((expr) ? 1 : 0)
                                  ^~~~
hb-unicode-private.hh:129:12: note: in expansion of macro ‘unlikely’
     return unlikely (hb_in_ranges (unicode,
            ^~~~~~~~
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:898:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2)
 ^~~~~~~~~~~~
hb-private.hh:898:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:131:26: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
        0xE0100u, 0xE01EFu));  /* VARIATION SELECTOR-17..256 */
                          ^
hb-private.hh:78:34: note: in definition of macro ‘_HB_BOOLEAN_EXPR’
 #define _HB_BOOLEAN_EXPR(expr) ((expr) ? 1 : 0)
                                  ^~~~
hb-unicode-private.hh:129:12: note: in expansion of macro ‘unlikely’
     return unlikely (hb_in_ranges (unicode,
            ^~~~~~~~
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:904:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2, T lo3, T hi3)
 ^~~~~~~~~~~~
hb-private.hh:904:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:131:26: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
        0xE0100u, 0xE01EFu));  /* VARIATION SELECTOR-17..256 */
                          ^
hb-private.hh:78:34: note: in definition of macro ‘_HB_BOOLEAN_EXPR’
 #define _HB_BOOLEAN_EXPR(expr) ((expr) ? 1 : 0)
                                  ^~~~
hb-unicode-private.hh:129:12: note: in expansion of macro ‘unlikely’
     return unlikely (hb_in_ranges (unicode,
            ^~~~~~~~
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh: In static member function ‘static hb_bool_t hb_unicode_funcs_t::is_default_ignorable(hb_codepoint_t)’:
hb-unicode-private.hh:182:53: error: no matching function for call to ‘hb_in_range(hb_codepoint_t&, unsigned int, unsigned int)’
  case 0x17: return hb_in_range (ch, 0x17B4u, 0x17B5u);
                                                     ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:883:1: note: candidate: template<class T> bool hb_in_range(T, T, T)
 hb_in_range (T u, T lo, T hi)
 ^~~~~~~~~~~
hb-private.hh:883:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:182:53: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
  case 0x17: return hb_in_range (ch, 0x17B4u, 0x17B5u);
                                                     ^
hb-unicode-private.hh:183:53: error: no matching function for call to ‘hb_in_range(hb_codepoint_t&, unsigned int, unsigned int)’
  case 0x18: return hb_in_range (ch, 0x180Bu, 0x180Eu);
                                                     ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:883:1: note: candidate: template<class T> bool hb_in_range(T, T, T)
 hb_in_range (T u, T lo, T hi)
 ^~~~~~~~~~~
hb-private.hh:883:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:183:53: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
  case 0x18: return hb_in_range (ch, 0x180Bu, 0x180Eu);
                                                     ^
hb-unicode-private.hh:186:26: error: no matching function for call to ‘hb_in_ranges(hb_codepoint_t&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)’
          0x2060u, 0x206Fu);
                          ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:898:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2)
 ^~~~~~~~~~~~
hb-private.hh:898:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:186:26: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
          0x2060u, 0x206Fu);
                          ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:904:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2, T lo3, T hi3)
 ^~~~~~~~~~~~
hb-private.hh:904:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:186:26: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
          0x2060u, 0x206Fu);
                          ^
hb-unicode-private.hh:187:53: error: no matching function for call to ‘hb_in_range(hb_codepoint_t&, unsigned int, unsigned int)’
  case 0xFE: return hb_in_range (ch, 0xFE00u, 0xFE0Fu) || ch == 0xFEFFu;
                                                     ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:883:1: note: candidate: template<class T> bool hb_in_range(T, T, T)
 hb_in_range (T u, T lo, T hi)
 ^~~~~~~~~~~
hb-private.hh:883:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:187:53: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
  case 0xFE: return hb_in_range (ch, 0xFE00u, 0xFE0Fu) || ch == 0xFEFFu;
                                                     ^
hb-unicode-private.hh:188:53: error: no matching function for call to ‘hb_in_range(hb_codepoint_t&, unsigned int, unsigned int)’
  case 0xFF: return hb_in_range (ch, 0xFFF0u, 0xFFF8u);
                                                     ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:883:1: note: candidate: template<class T> bool hb_in_range(T, T, T)
 hb_in_range (T u, T lo, T hi)
 ^~~~~~~~~~~
hb-private.hh:883:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:188:53: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
  case 0xFF: return hb_in_range (ch, 0xFFF0u, 0xFFF8u);
                                                     ^
hb-unicode-private.hh:197:28: error: no matching function for call to ‘hb_in_ranges(hb_codepoint_t&, unsigned int, unsigned int, unsigned int, unsigned int)’
          0x1D173u, 0x1D17Au);
                            ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:898:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2)
 ^~~~~~~~~~~~
hb-private.hh:898:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:197:28: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
          0x1D173u, 0x1D17Au);
                            ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:904:1: note: candidate: template<class T> bool hb_in_ranges(T, T, T, T, T, T, T)
 hb_in_ranges (T u, T lo1, T hi1, T lo2, T hi2, T lo3, T hi3)
 ^~~~~~~~~~~~
hb-private.hh:904:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:197:28: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
          0x1D173u, 0x1D17Au);
                            ^
hb-unicode-private.hh:198:55: error: no matching function for call to ‘hb_in_range(hb_codepoint_t&, unsigned int, unsigned int)’
  case 0x0E: return hb_in_range (ch, 0xE0000u, 0xE0FFFu);
                                                       ^
In file included from hb-buffer-private.hh:33:0,
                 from hb-buffer-serialize.cc:27:
hb-private.hh:883:1: note: candidate: template<class T> bool hb_in_range(T, T, T)
 hb_in_range (T u, T lo, T hi)
 ^~~~~~~~~~~
hb-private.hh:883:1: note:   template argument deduction/substitution failed:
In file included from hb-buffer-private.hh:35:0,
                 from hb-buffer-serialize.cc:27:
hb-unicode-private.hh:198:55: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int’ and ‘unsigned int’)
  case 0x0E: return hb_in_range (ch, 0xE0000u, 0xE0FFFu);
                                                       ^
Makefile:1938: recipe for target 'libharfbuzz_la-hb-buffer-serialize.lo' failed
```

### PR DESCRIPTION
**Pull request by ebraminio**
This Is a part of porting harfbuz to vitasdk, I guess "src/hb-ot-layout.cc" change part, specially, needs more careful reviewing.

### CODE REVIEW

File: src/hb-common.cc [hunk 1]
```diff
@@ -792,8 +792,8 @@ static bool
 parse_feature_value_postfix (const char **pp, const char *end, hb_feature_t *feature)
 {
   bool had_equal = parse_char (pp, end, '=');
-  bool had_value = parse_uint (pp, end, &feature->value) ||
-                   parse_bool (pp, end, &feature->value);
+  bool had_value = parse_uint (pp, end, (unsigned int*) &feature->value) ||
+                   parse_bool (pp, end, (unsigned int*) &feature->value);
```
Comment (ebraminio) [inline src/hb-common.cc]: This needs more attention I guess

File: src/hb-ot-layout.cc [hunk 2]
```diff
@@ -281,7 +281,8 @@ hb_ot_layout_get_ligature_carets (hb_font_t      *font,
 				  unsigned int   *caret_count /* IN/OUT */,
 				  int            *caret_array /* OUT */)
 {
-  return _get_gdef (font->face).get_lig_carets (font, direction, glyph, start_offset, caret_count, caret_array);
+  return _get_gdef (font->face).get_lig_carets (font, direction, glyph, start_offset,
+    caret_count, (hb_position_t*) caret_array);
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: This also

**Comment by ebraminio** [comment]
This makes vitasdk package builder CI work also: https://github.com/vitasdk/packages/pull/28

File: src/hb-ot-layout.cc [hunk 3]
```diff
@@ -279,10 +279,9 @@ hb_ot_layout_get_ligature_carets (hb_font_t      *font,
 				  hb_codepoint_t  glyph,
 				  unsigned int    start_offset,
 				  unsigned int   *caret_count /* IN/OUT */,
-				  int            *caret_array /* OUT */)
+				  hb_position_t  *caret_array /* OUT */)
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: Now it matches with its actual signature on [src/hb-ot-layout.h](https://github.com/ebraminio/harfbuzz/blob/master/src/hb-ot-layout.h#L88)

File: src/hb-common.cc [hunk 4]
```diff
@@ -671,6 +671,30 @@ parse_uint (const char **pp, const char *end, unsigned int *pv)
 }
 
 static bool
+parse_uint32 (const char **pp, const char *end, uint32_t *pv)
```
Comment (ebraminio) [inline src/hb-common.cc]: Duplication of parse_uint, no template please as it opens another can of worms on different platforms I'd think :)

File: src/hb-ot-shape-complex-arabic-table.hh [hunk 5]
```diff
@@ -139,28 +139,28 @@ joining_type (hb_codepoint_t u)
   switch (u >> 12)
   {
     case 0x0u:
-      if (hb_in_range (u, 0x0600u, 0x08E2u)) return joining_table[u - 0x0600u + joining_offset_0x0600u];
+      if (hb_in_range<hb_codepoint_t> (u, 0x0600u, 0x08E2u)) return joining_table[u - 0x0600u + joining_offset_0x0600u];
```
Comment (ebraminio) [inline src/hb-ot-shape-complex-arabic-table.hh]: If I change 0x0600u to 0x0600uL it works arm-none-eabi but not on my default build system, so best way here would be disambiguating it I'd guess.

File: src/hb-ot-font.cc [hunk 6]
```diff
@@ -44,7 +44,7 @@
 struct hb_ot_face_metrics_accelerator_t
 {
   unsigned int num_metrics;
-  unsigned int num_advances;
+  uint32_t num_advances;
```
Comment (ebraminio) [inline src/hb-ot-font.cc]: needed as https://github.com/behdad/harfbuzz/blob/79e8e27ffd3da29ca27d3aebd2ef425bf1cb7f9d/src/hb-ot-font.cc#L141 glyph is uint32_t so this should be also (or I should cast there instead)

Comment (behdad) [inline src/hb-ot-font.cc]: Meh.  This case, cast would have been nice.  But doesn't matter.  Maybe change `num_metrics` to uint32_t as well?

File: src/hb-ot-shape-complex-arabic-table.hh (hunk 5 above)
Comment (behdad) [inline src/hb-ot-shape-complex-arabic-table.hh]: Another option would be to define a macro U:

```
#define U(v) ((hb_codepoint_t) (v))

and then use `U(0x0600)` etc.  Or even further, dropping the 0x, so we can say eg. `u(0600)`.  But we can do that in the future.

File: src/hb-common.cc (hunk 1 above)
Comment (behdad) [inline src/hb-common.cc]: Another option would be to define a local variable of appropriate type, and assign that to `feature->value` later.  Then you wouldn't need duplicating `parse_uint` and `parse_bool` etc.

**Comment by behdad** [comment]
As we discussed yesterday, the ` (unsigned int*) &feature->value` is not correct.  Feel free to merge after addressing that one.  I left a few other comments as well, feel free to address.

File: src/hb-common.cc (hunk 1 above)
Comment (ebraminio) [inline src/hb-common.cc]: This is the old version

File: src/hb-ot-font.cc (hunk 6 above)
Comment (ebraminio) [inline src/hb-ot-font.cc]: np, went for cast

File: src/hb-ot-shape-complex-arabic-table.hh (hunk 5 above)
Comment (ebraminio) [inline src/hb-ot-shape-complex-arabic-table.hh]: I was doing this but found out U already has a conflicting [use](https://github.com/behdad/harfbuzz/blob/02bfd965af588640250c47f344ad3096c8a373e0/src/hb-ot-shape-complex-arabic-table.hh#L23).

Not in favor of u() personally as it will obfuscating things more on my view, lets defer it if is possible.

File: src/hb-common.cc (hunk 1 above)
Comment (ebraminio) [inline src/hb-common.cc]: On that case I should interfere more with the logic as putting result on the OUT parameter is not happening always so I should check one first then the other ... let defer that.

File: src/hb-ot-font.cc [hunk 7]
```diff
@@ -138,7 +138,7 @@ struct hb_ot_face_metrics_accelerator_t
 	return this->default_advance;
     }
 
-    return this->table->longMetric[MIN (glyph, this->num_advances - 1)].advance
+    return this->table->longMetric[MIN (glyph, (uint32_t) this->num_advances - 1)].advance
```
Comment (ebraminio) [inline src/hb-ot-font.cc]: As requested instead interfering with "num_advances"

File: CMakeLists.txt [hunk 8]
```diff
@@ -128,7 +128,7 @@ set(HB_VERSION_MICRO ${CMAKE_MATCH_4})
 
 ## Define ragel tasks
 if (NOT IN_HB_DIST)
-  find_program(RAGEL "ragel")
+  find_program(RAGEL "ragel" CMAKE_FIND_ROOT_PATH_BOTH)
```
Comment (ebraminio) [inline CMakeLists.txt]: So it can find ragel on vitasdk environment.

File: CMakeLists.txt [hunk 9]
```diff
@@ -71,7 +71,7 @@ endif ()
 
 ## Detect if we are running inside a distribution or regular repository folder
 set(IN_HB_DIST FALSE)
-if (EXISTS "${PROJECT_SOURCE_DIR}/src/hb-version.h")
+if (EXISTS "${PROJECT_SOURCE_DIR}/ChangeLog")
```
Comment (ebraminio) [inline CMakeLists.txt]: Better is-in-distribution check

**Comment by behdad** [comment]
Thanks. Please merge as you see fit (and if the bots are green).
