### PR TITLE
Fix for reordering of Tibetan vowel u

### LINKED ISSUE #417: Rendering for Tibetan long vowel U is broken
On Linux and Android, the Tibetan syllable U (ཨཱུ) is rendered incorrectly.

The following site shows the browser-output when rendering hUM and U, together with bitmaps for the correctly rendered glyphs: [Test-site](http://digitaltibetan.org/index.php/Tibetan_Unicode_Test_Page#Harfbuzz_test)

Affected are:
* Android (tested with 7.1.2beta)
* Linux (tested with harfbuzz 1.4.2)
* macOS & Chrome: rendering seems ok within macOS fonts Kokonor and Kailasa, but breaks with all other Tibetan fonts tested.

### PR DESCRIPTION
**Pull request by domschl**
Following the discoveries of @eroux, discussion in #417, this minimal change to 2f560ee44b7b08683e8e6955fe3b95187e8bda32 seems to fix the rendering of long Tibetan vowel U, fixes #417.

### CODE REVIEW

**Comment by dscorbett** [comment]
The comment a few lines above (“Modify U+0F74 (ccc=132) to reorder before ccc=130 marks.”) is now wrong.

**Comment by eroux** [comment]
@domschl there are some tests for Tibetan in `/test/shaping/texts/in-tree/shaper-tibetan/script-tibetan/misc` did you try to run them? (there are some scripts for that in the root directory of the repo) also, I think it would be good to add a test for `ཨཱུ` in these tests, wdyt?

**Comment by domschl** [comment]
I've cleaned up the comment, @behdad needs to check this. Reordering vowel u before 130 breaks the long u.

**Comment by domschl** [comment]
@eroux : Shaping tests as part of the harfbuzz test-suite for the Tibetan vowels are now added in pull-request #446 .

We could of course add more tests?
I had a look at `/harfbuzz/test/shaping/texts/in-tree/shaper-tibetan/script-tibetan/misc`, but the sample-text contains entries that to my knowledge are neither valid Tibetan nor Sanskrit-transliterations: some seem to be transcriptions of dbu med shorthands, anyway I don't know what to do with those files. Ideas?

**Comment by KrasnayaPloshchad** [comment]
What happened if you tested with [Tibetan shorthand contractions](http://www.babelstone.co.uk/Tibetan/Contractions.html)?

**Comment by eroux** [comment]
(we cross-posted, I answered your question on https://github.com/behdad/harfbuzz/pull/446#issuecomment-289271278 I think)

**Comment by domschl** [comment]
This pull-request slightly changes the reordering of vowel-signs: in case of multiple vowel-signs, u is moved ahead, but not ahead of achung. That way long-u renders correctly, and contraction-multiple-vowels are supported.

**Comment by eroux** [comment]
@behdad do you think this could be merged?

**Comment by domschl** [comment]
@behdad, please comment: is there anything that can be done to get this merged?

File: src/hb-unicode-private.hh [hunk 1]
```diff
@@ -345,10 +345,17 @@ extern HB_INTERNAL const hb_unicode_funcs_t _hb_unicode_funcs_nil;
...
+ * 
+ * In case of multiple vowel-signs, use u first (but after achung) 
+ * this allows Dzongkha multi-vowel shortcuts to render correctly 
+ */
 #define HB_MODIFIED_COMBINING_CLASS_CCC129 129 /* sign aa */
-#define HB_MODIFIED_COMBINING_CLASS_CCC130 130 /* sign i */
-#define HB_MODIFIED_COMBINING_CLASS_CCC132 132 /* sign u */
+#define HB_MODIFIED_COMBINING_CLASS_CCC130 132 /* sign i */
+#define HB_MODIFIED_COMBINING_CLASS_CCC132 131 /* sign u */
+#define HB_MODIFIED_COMBINING_CLASS_CCC138 138 /* sign e */
```
Comment (behdad) [inline src/hb-unicode-private.hh]: The 138 and 140 lines are ignored, because they are not hooked up in hb-unicode.cc:_hb_modified_combining_class.  So, this is not doing what you think it does.  Please fix and test again.  I don't know when I'll have time to review thoroughly and make sure this doesn't break all the cases I had deliberately fixed before, but I'll try.  Thanks.

**Comment by domschl** [comment]
Thanks @behdad , your are right, 138 and 140 were mistakenly added (test-mistake on my part), and are now removed. I've increased the test-coverage for contractions in #446 for cover all the multi-vowel cases from the test-texts [Now 113 test cases]. Even if the resulting fonts-files (100kb, 120kb) are too large to be included on the long run, the larger and more complete tests hopefully help with evaluating this fix.

**Comment by domschl** [comment]
@behdad, please consider merging this:
- The change is minmal (one line) and addresses exactly what was broken by 2f560ee44b7b08683e8e6955fe3b95187e8bda32 : preventing vowel u to be reordered before achung (which is a bug).
- While there was a work-around for the malfunctioning contractions that were fixed by the previous commit (one could simply use the expanded version), there is _no_ workaround for the currently broken long-U.
- We did not have tests before, now we do have tests for Tibetan, for both contractions and vowels.
If there is anything I can do to get this done, please let me know.

**Comment by behdad** [comment]
Will do.  Thanks.

**Comment by eroux** [comment]
@behdad do you think you could review this PR?
